#### Prerequisite

In [1]:
#Load SQL module

%load_ext sql

In [2]:
#Connect to the database

%sql mysql://root:****@localhost:3306/mydatadb

'Connected: root@mydatadb'

## Data Exploration

Select data and take a look of the dataset

In [7]:
%%sql

SELECT *
FROM covid_deaths
LIMIT 5;

 * mysql://root:***@localhost:3306/mydatadb
5 rows affected.

[('AFG', 'Asia', 'Afghanistan', datetime.datetime(2020, 2, 24, 0, 0), 1.0, 1.0, None, None, None, None, 0.026, 0.026, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 8.33, 38928341.0, 54.422, 18.6, 2.581, 1.337, 1803.987, None, 597.029, 9.59, None, None, 37.746, 0.5, 64.83, 0.511),
 ('AFG', 'Asia', 'Afghanistan', datetime.datetime(2020, 2, 25, 0, 0), 1.0, 0.0, None, None, None, None, 0.026, 0.0, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 8.33, 38928341.0, 54.422, 18.6, 2.581, 1.337, 1803.987, None, 597.029, 9.59, None, None, 37.746, 0.5, 64.83, 0.511),
 ('AFG', 'Asia', 'Afghanistan', datetime.datetime(2020, 2, 26, 0, 0), 1.0, 0.0, None, None, None, None, 0.026, 0.0, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 8.33, 38928341.0, 54.422, 18.6, 2.581, 1.337, 1803.987, None, 597.029, 9.59, None, None, 37.746, 0.5, 64.83, 0.511),
 ('AFG', 'Asia', 'Afghanistan', datetime.datetime(2020, 2, 27, 0, 0), 1.0, 0.0, None, None, None, None, 0.026, 0.0, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 8.33, 38928341.0, 54.422, 18.6, 2.581, 1.337, 1803.987, None, 597.029, 9.59, None, None, 37.746, 0.5, 64.83, 0.511),
 ('AFG', 'Asia', 'Afghanistan', datetime.datetime(2020, 2, 28, 0, 0), 1.0, 0.0, None, None, None, None, 0.026, 0.0, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 8.33, 38928341.0, 54.422, 18.6, 2.581, 1.337, 1803.987, None, 597.029, 9.59, None, None, 37.746, 0.5, 64.83, 0.511)]

As we can see, We have tons of data and many columns. We are not gonna work on all of them but few. Lets select toal_cases, new_cases, total_deaths and poplution.

In [16]:
%%sql

SELECT location, date, total_cases, new_cases, total_deaths, population
FROM covid_deaths
ORDER BY 2
LIMIT 100;

 * mysql://root:***@localhost:3306/mydatadb
100 rows affected.

[('Mexico', datetime.datetime(2020, 1, 1, 0, 0), None, None, None, 128932753.0),
 ('Argentina', datetime.datetime(2020, 1, 1, 0, 0), None, None, None, 45195777.0),
 ('Argentina', datetime.datetime(2020, 1, 2, 0, 0), None, None, None, 45195777.0),
 ('Mexico', datetime.datetime(2020, 1, 2, 0, 0), None, None, None, 128932753.0),
 ('Mexico', datetime.datetime(2020, 1, 3, 0, 0), None, None, None, 128932753.0),
 ('Argentina', datetime.datetime(2020, 1, 3, 0, 0), None, None, None, 45195777.0),
 ('Argentina', datetime.datetime(2020, 1, 4, 0, 0), None, None, None, 45195777.0),
 ('Mexico', datetime.datetime(2020, 1, 4, 0, 0), None, None, None, 128932753.0),
 ('Thailand', datetime.datetime(2020, 1, 4, 0, 0), None, None, None, 69799978.0),
 ('Thailand', datetime.datetime(2020, 1, 5, 0, 0), None, None, None, 69799978.0),
 ('Argentina', datetime.datetime(2020, 1, 5, 0, 0), None, None, None, 45195777.0),
 ('Mexico', datetime.datetime(2020, 1, 5, 0, 0), None, None, None, 128932753.0),
 ('Mexico', datetime.datetime(2020, 1, 6, 0, 0), None, None, None, 128932753.0),
 ('Thailand', datetime.datetime(2020, 1, 6, 0, 0), None, None, None, 69799978.0),
 ('Peru', datetime.datetime(2020, 1, 6, 0, 0), None, None, None, 32971846.0),
 ('Argentina', datetime.datetime(2020, 1, 6, 0, 0), None, None, None, 45195777.0),
 ('Argentina', datetime.datetime(2020, 1, 7, 0, 0), None, None, None, 45195777.0),
 ('Mexico', datetime.datetime(2020, 1, 7, 0, 0), None, None, None, 128932753.0),
 ('Peru', datetime.datetime(2020, 1, 7, 0, 0), None, None, None, 32971846.0),
 ('Thailand', datetime.datetime(2020, 1, 7, 0, 0), None, None, None, 69799978.0),
 ('Thailand', datetime.datetime(2020, 1, 8, 0, 0), None, None, None, 69799978.0),
 ('Peru', datetime.datetime(2020, 1, 8, 0, 0), None, None, None, 32971846.0),
 ('Argentina', datetime.datetime(2020, 1, 8, 0, 0), None, None, None, 45195777.0),
 ('Mexico', datetime.datetime(2020, 1, 8, 0, 0), None, None, None, 128932753.0),
 ('Mexico', datetime.datetime(2020, 1, 9, 0, 0), None, None, None, 128932753.0),
 ('Peru', datetime.datetime(2020, 1, 9, 0, 0), None, None, None, 32971846.0),
 ('Thailand', datetime.datetime(2020, 1, 9, 0, 0), None, None, None, 69799978.0),
 ('Argentina', datetime.datetime(2020, 1, 9, 0, 0), None, None, None, 45195777.0),
 ('Argentina', datetime.datetime(2020, 1, 10, 0, 0), None, None, None, 45195777.0),
 ('Mexico', datetime.datetime(2020, 1, 10, 0, 0), None, None, None, 128932753.0),
 ('Thailand', datetime.datetime(2020, 1, 10, 0, 0), None, None, None, 69799978.0),
 ('Peru', datetime.datetime(2020, 1, 10, 0, 0), None, None, None, 32971846.0),
 ('Peru', datetime.datetime(2020, 1, 11, 0, 0), None, None, None, 32971846.0),
 ('Thailand', datetime.datetime(2020, 1, 11, 0, 0), None, None, None, 69799978.0),
 ('Argentina', datetime.datetime(2020, 1, 11, 0, 0), None, None, None, 45195777.0),
 ('Mexico', datetime.datetime(2020, 1, 11, 0, 0), None, None, None, 128932753.0),
 ('Mexico', datetime.datetime(2020, 1, 12, 0, 0), None, None, None, 128932753.0),
 ('Thailand', datetime.datetime(2020, 1, 12, 0, 0), None, None, None, 69799978.0),
 ('Peru', datetime.datetime(2020, 1, 12, 0, 0), None, None, None, 32971846.0),
 ('Argentina', datetime.datetime(2020, 1, 12, 0, 0), None, None, None, 45195777.0),
 ('Argentina', datetime.datetime(2020, 1, 13, 0, 0), None, None, None, 45195777.0),
 ('Mexico', datetime.datetime(2020, 1, 13, 0, 0), None, None, None, 128932753.0),
 ('Peru', datetime.datetime(2020, 1, 13, 0, 0), None, None, None, 32971846.0),
 ('Thailand', datetime.datetime(2020, 1, 13, 0, 0), None, None, None, 69799978.0),
 ('Thailand', datetime.datetime(2020, 1, 14, 0, 0), None, None, None, 69799978.0),
 ('Peru', datetime.datetime(2020, 1, 14, 0, 0), None, None, None, 32971846.0),
 ('Argentina', datetime.datetime(2020, 1, 14, 0, 0), None, None, None, 45195777.0),
 ('Mexico', datetime.datetime(2020, 1, 14, 0, 0), None, None, None, 128932753.0),
 ('Mexico', datetime.datetime(2020, 1, 15, 0, 0), None, None, None, 128932753.0),
 ('Peru', datetime.datetime(2020, 1, 15, 0, 0), None, None, None, 32971846.0),
 ('Thailand', datetime.datetime(2020, 1, 15, 0, 0), None, None, None, 69799978.0),
 ('Argentina', datetime.datetime(2020, 1, 15, 0, 0), None, None, None, 45195777.0),
 ('Argentina', datetime.datetime(2020, 1, 16, 0, 0), None, None, None, 45195777.0),
 ('Mexico', datetime.datetime(2020, 1, 16, 0, 0), None, None, None, 128932753.0),
 ('Thailand', datetime.datetime(2020, 1, 16, 0, 0), None, None, None, 69799978.0),
 ('Peru', datetime.datetime(2020, 1, 16, 0, 0), None, None, None, 32971846.0),
 ('Taiwan', datetime.datetime(2020, 1, 16, 0, 0), None, None, None, 23816775.0),
 ('Taiwan', datetime.datetime(2020, 1, 17, 0, 0), None, None, None, 23816775.0),
 ('Peru', datetime.datetime(2020, 1, 17, 0, 0), None, None, None, 32971846.0),
 ('Thailand', datetime.datetime(2020, 1, 17, 0, 0), None, None, None, 69799978.0),
 ('Argentina', datetime.datetime(2020, 1, 17, 0, 0), None, None, None, 45195777.0),
 ('Mexico', datetime.datetime(2020, 1, 17, 0, 0), None, None, None, 128932753.0),
 ('Mexico', datetime.datetime(2020, 1, 18, 0, 0), None, None, None, 128932753.0),
 ('Thailand', datetime.datetime(2020, 1, 18, 0, 0), None, None, None, 69799978.0),
 ('Peru', datetime.datetime(2020, 1, 18, 0, 0), None, None, None, 32971846.0),
 ('Taiwan', datetime.datetime(2020, 1, 18, 0, 0), None, None, None, 23816775.0),
 ('Argentina', datetime.datetime(2020, 1, 18, 0, 0), None, None, None, 45195777.0),
 ('Argentina', datetime.datetime(2020, 1, 19, 0, 0), None, None, None, 45195777.0),
 ('Mexico', datetime.datetime(2020, 1, 19, 0, 0), None, None, None, 128932753.0),
 ('Taiwan', datetime.datetime(2020, 1, 19, 0, 0), None, None, None, 23816775.0),
 ('Peru', datetime.datetime(2020, 1, 19, 0, 0), None, None, None, 32971846.0),
 ('Thailand', datetime.datetime(2020, 1, 19, 0, 0), None, None, None, 69799978.0),
 ('Thailand', datetime.datetime(2020, 1, 20, 0, 0), None, None, None, 69799978.0),
 ('Peru', datetime.datetime(2020, 1, 20, 0, 0), None, None, None, 32971846.0),
 ('Taiwan', datetime.datetime(2020, 1, 20, 0, 0), None, None, None, 23816775.0),
 ('Argentina', datetime.datetime(2020, 1, 20, 0, 0), None, None, None, 45195777.0),
 ('Mexico', datetime.datetime(2020, 1, 20, 0, 0), None, None, None, 128932753.0),
 ('Mexico', datetime.datetime(2020, 1, 21, 0, 0), None, None, None, 128932753.0),
 ('Taiwan', datetime.datetime(2020, 1, 21, 0, 0), None, None, None, 23816775.0),
 ('South Korea', datetime.datetime(2020, 1, 21, 0, 0), None, None, None, 51269183.0),
 ('Peru', datetime.datetime(2020, 1, 21, 0, 0), None, None, None, 32971846.0),
 ('Thailand', datetime.datetime(2020, 1, 21, 0, 0), None, None, None, 69799978.0),
 ('Argentina', datetime.datetime(2020, 1, 21, 0, 0), None, None, None, 45195777.0),
 ('Argentina', datetime.datetime(2020, 1, 22, 0, 0), None, None, None, 45195777.0),
 ('China', datetime.datetime(2020, 1, 22, 0, 0), 548.0, None, 17.0, 1439323774.0),
 ('Asia', datetime.datetime(2020, 1, 22, 0, 0), 556.0, 0.0, 17.0, 4639847425.0),
 ('Mexico', datetime.datetime(2020, 1, 22, 0, 0), None, None, None, 128932753.0),
 ('Japan', datetime.datetime(2020, 1, 22, 0, 0), 2.0, None, None, 126476458.0),
 ('Thailand', datetime.datetime(2020, 1, 22, 0, 0), 4.0, None, None, 69799978.0),
 ('Taiwan', datetime.datetime(2020, 1, 22, 0, 0), 1.0, None, None, 23816775.0),
 ('World', datetime.datetime(2020, 1, 22, 0, 0), 557.0, 0.0, 17.0, 7794798729.0),
 ('United States', datetime.datetime(2020, 1, 22, 0, 0), 1.0, None, None, 331002647.0),
 ('North America', datetime.datetime(2020, 1, 22, 0, 0), 1.0, 0.0, None, 592072204.0),
 ('Peru', datetime.datetime(2020, 1, 22, 0, 0), None, None, None, 32971846.0),
 ('South Korea', datetime.datetime(2020, 1, 22, 0, 0), 1.0, None, None, 51269183.0),
 ('Singapore', datetime.datetime(2020, 1, 23, 0, 0), 1.0, 1.0, None, 5850343.0),
 ('South Korea', datetime.datetime(2020, 1, 23, 0, 0), 1.0, 0.0, None, 51269183.0),
 ('United States', datetime.datetime(2020, 1, 23, 0, 0), 1.0, 0.0, None, 331002647.0),
 ('Taiwan', datetime.datetime(2020, 1, 23, 0, 0), 1.0, 0.0, None, 23816775.0),
 ('Thailand', datetime.datetime(2020, 1, 23, 0, 0), 4.0, 0.0, None, 69799978.0)]

BY running the query above we can clearly see that the first ever infected cases and deaths were spoted in china on January 22, 2020. Total death counted that day is 17 and total cases were 548.

Lets find out the overall death ratio compared to total cases from my home country which is Bangladesh.

In [27]:
%%sql 

-- Total Cases vs Total Deaths

SELECT location, date, total_cases, total_deaths, (total_deaths/total_cases)*100 AS Death_percentage
FROM covid_deaths
WHERE location like '%desh%' and continent is not null
ORDER BY 5 DESC, 2
LIMIT 100;

 * mysql://root:***@localhost:3306/mydatadb
100 rows affected.

[('Bangladesh', datetime.datetime(2020, 3, 25, 0, 0), 39.0, 5.0, 12.82051282051282),
 ('Bangladesh', datetime.datetime(2020, 4, 4, 0, 0), 70.0, 8.0, 11.428571428571429),
 ('Bangladesh', datetime.datetime(2020, 3, 26, 0, 0), 44.0, 5.0, 11.363636363636363),
 ('Bangladesh', datetime.datetime(2020, 4, 1, 0, 0), 54.0, 6.0, 11.11111111111111),
 ('Bangladesh', datetime.datetime(2020, 4, 2, 0, 0), 56.0, 6.0, 10.714285714285714),
 ('Bangladesh', datetime.datetime(2020, 3, 27, 0, 0), 48.0, 5.0, 10.416666666666668),
 ('Bangladesh', datetime.datetime(2020, 3, 28, 0, 0), 48.0, 5.0, 10.416666666666668),
 ('Bangladesh', datetime.datetime(2020, 3, 29, 0, 0), 48.0, 5.0, 10.416666666666668),
 ('Bangladesh', datetime.datetime(2020, 4, 7, 0, 0), 164.0, 17.0, 10.365853658536585),
 ('Bangladesh', datetime.datetime(2020, 3, 24, 0, 0), 39.0, 4.0, 10.256410256410255),
 ('Bangladesh', datetime.datetime(2020, 4, 5, 0, 0), 88.0, 9.0, 10.227272727272728),
 ('Bangladesh', datetime.datetime(2020, 3, 30, 0, 0), 49.0, 5.0, 10.204081632653061),
 ('Bangladesh', datetime.datetime(2020, 4, 3, 0, 0), 61.0, 6.0, 9.836065573770492),
 ('Bangladesh', datetime.datetime(2020, 3, 31, 0, 0), 51.0, 5.0, 9.803921568627452),
 ('Bangladesh', datetime.datetime(2020, 4, 6, 0, 0), 123.0, 12.0, 9.75609756097561),
 ('Bangladesh', datetime.datetime(2020, 4, 8, 0, 0), 218.0, 20.0, 9.174311926605505),
 ('Bangladesh', datetime.datetime(2020, 3, 23, 0, 0), 33.0, 3.0, 9.090909090909092),
 ('Bangladesh', datetime.datetime(2020, 3, 21, 0, 0), 25.0, 2.0, 8.0),
 ('Bangladesh', datetime.datetime(2020, 3, 22, 0, 0), 27.0, 2.0, 7.4074074074074066),
 ('Bangladesh', datetime.datetime(2020, 3, 18, 0, 0), 14.0, 1.0, 7.142857142857142),
 ('Bangladesh', datetime.datetime(2020, 4, 10, 0, 0), 424.0, 27.0, 6.367924528301887),
 ('Bangladesh', datetime.datetime(2020, 4, 9, 0, 0), 330.0, 21.0, 6.363636363636363),
 ('Bangladesh', datetime.datetime(2020, 4, 11, 0, 0), 482.0, 30.0, 6.224066390041494),
 ('Bangladesh', datetime.datetime(2020, 3, 19, 0, 0), 17.0, 1.0, 5.88235294117647),
 ('Bangladesh', datetime.datetime(2020, 4, 12, 0, 0), 621.0, 34.0, 5.475040257648954),
 ('Bangladesh', datetime.datetime(2020, 3, 20, 0, 0), 20.0, 1.0, 5.0),
 ('Bangladesh', datetime.datetime(2020, 4, 13, 0, 0), 803.0, 39.0, 4.85678704856787),
 ('Bangladesh', datetime.datetime(2020, 4, 14, 0, 0), 1012.0, 46.0, 4.545454545454546),
 ('Bangladesh', datetime.datetime(2020, 4, 17, 0, 0), 1838.0, 75.0, 4.080522306855277),
 ('Bangladesh', datetime.datetime(2020, 4, 15, 0, 0), 1231.0, 50.0, 4.061738424045491),
 ('Bangladesh', datetime.datetime(2020, 4, 18, 0, 0), 2144.0, 84.0, 3.9179104477611943),
 ('Bangladesh', datetime.datetime(2020, 4, 16, 0, 0), 1572.0, 60.0, 3.816793893129771),
 ('Bangladesh', datetime.datetime(2020, 4, 19, 0, 0), 2456.0, 91.0, 3.705211726384365),
 ('Bangladesh', datetime.datetime(2020, 4, 20, 0, 0), 2948.0, 101.0, 3.426051560379918),
 ('Bangladesh', datetime.datetime(2020, 4, 21, 0, 0), 3382.0, 110.0, 3.252513305736251),
 ('Bangladesh', datetime.datetime(2020, 4, 22, 0, 0), 3772.0, 120.0, 3.1813361611876987),
 ('Bangladesh', datetime.datetime(2020, 4, 23, 0, 0), 4186.0, 127.0, 3.0339225991399905),
 ('Bangladesh', datetime.datetime(2020, 4, 25, 0, 0), 4998.0, 140.0, 2.801120448179272),
 ('Bangladesh', datetime.datetime(2020, 4, 24, 0, 0), 4689.0, 131.0, 2.793772659415654),
 ('Bangladesh', datetime.datetime(2020, 4, 26, 0, 0), 5416.0, 145.0, 2.6772525849335302),
 ('Bangladesh', datetime.datetime(2020, 4, 27, 0, 0), 5913.0, 152.0, 2.5706071368171823),
 ('Bangladesh', datetime.datetime(2020, 4, 28, 0, 0), 6462.0, 155.0, 2.3986381925100586),
 ('Bangladesh', datetime.datetime(2020, 4, 29, 0, 0), 7103.0, 163.0, 2.2948050119667744),
 ('Bangladesh', datetime.datetime(2020, 4, 30, 0, 0), 7667.0, 168.0, 2.19120907786618),
 ('Bangladesh', datetime.datetime(2020, 5, 1, 0, 0), 8238.0, 170.0, 2.0636076717649914),
 ('Bangladesh', datetime.datetime(2020, 5, 2, 0, 0), 8790.0, 175.0, 1.9908987485779295),
 ('Bangladesh', datetime.datetime(2020, 5, 3, 0, 0), 9455.0, 177.0, 1.8720253833950289),
 ('Bangladesh', datetime.datetime(2020, 5, 4, 0, 0), 10143.0, 182.0, 1.7943409247757072),
 ('Bangladesh', datetime.datetime(2020, 5, 5, 0, 0), 10929.0, 183.0, 1.674444139445512),
 ('Bangladesh', datetime.datetime(2020, 5, 7, 0, 0), 12425.0, 199.0, 1.6016096579476864),
 ('Bangladesh', datetime.datetime(2020, 5, 6, 0, 0), 11719.0, 186.0, 1.5871661404556703),
 ('Bangladesh', datetime.datetime(2020, 5, 8, 0, 0), 13134.0, 206.0, 1.568448302116644),
 ('Bangladesh', datetime.datetime(2020, 5, 10, 0, 0), 14657.0, 228.0, 1.5555707170635191),
 ('Bangladesh', datetime.datetime(2020, 5, 9, 0, 0), 13770.0, 214.0, 1.5541031227305737),
 ('Bangladesh', datetime.datetime(2021, 2, 28, 0, 0), 546216.0, 8408.0, 1.5393177790471169),
 ('Bangladesh', datetime.datetime(2021, 2, 26, 0, 0), 545424.0, 8395.0, 1.5391695268268355),
 ('Bangladesh', datetime.datetime(2021, 3, 1, 0, 0), 546801.0, 8416.0, 1.5391339811009854),
 ('Bangladesh', datetime.datetime(2021, 2, 23, 0, 0), 544116.0, 8374.0, 1.539010064030464),
 ('Bangladesh', datetime.datetime(2021, 3, 2, 0, 0), 547316.0, 8423.0, 1.5389646931571523),
 ('Bangladesh', datetime.datetime(2021, 2, 27, 0, 0), 545831.0, 8400.0, 1.5389378763756547),
 ('Bangladesh', datetime.datetime(2021, 2, 24, 0, 0), 544544.0, 8379.0, 1.5387186343068695),
 ('Bangladesh', datetime.datetime(2021, 2, 25, 0, 0), 544954.0, 8384.0, 1.5384784770824695),
 ('Bangladesh', datetime.datetime(2021, 3, 3, 0, 0), 547930.0, 8428.0, 1.5381526837369737),
 ('Bangladesh', datetime.datetime(2021, 3, 8, 0, 0), 551175.0, 8476.0, 1.5378055971333968),
 ('Bangladesh', datetime.datetime(2021, 3, 4, 0, 0), 548549.0, 8435.0, 1.5376930775555147),
 ('Bangladesh', datetime.datetime(2021, 3, 7, 0, 0), 550330.0, 8462.0, 1.5376228808169645),
 ('Bangladesh', datetime.datetime(2021, 3, 9, 0, 0), 552087.0, 8489.0, 1.5376199765616652),
 ('Bangladesh', datetime.datetime(2021, 3, 6, 0, 0), 549724.0, 8451.0, 1.5373169081211664),
 ('Bangladesh', datetime.datetime(2021, 3, 5, 0, 0), 549184.0, 8441.0, 1.5370076331429903),
 ('Bangladesh', datetime.datetime(2021, 2, 22, 0, 0), 543717.0, 8356.0, 1.5368289018000172),
 ('Bangladesh', datetime.datetime(2021, 2, 21, 0, 0), 543351.0, 8349.0, 1.536575804590403),
 ('Bangladesh', datetime.datetime(2021, 2, 19, 0, 0), 542674.0, 8337.0, 1.5362814507420661),
 ('Bangladesh', datetime.datetime(2021, 2, 20, 0, 0), 543024.0, 8342.0, 1.5362120274610331),
 ('Bangladesh', datetime.datetime(2021, 3, 10, 0, 0), 553105.0, 8496.0, 1.5360555409913128),
 ('Bangladesh', datetime.datetime(2021, 2, 18, 0, 0), 542268.0, 8329.0, 1.535956390567026),
 ('Bangladesh', datetime.datetime(2021, 2, 17, 0, 0), 541877.0, 8314.0, 1.5342965285479915),
 ('Bangladesh', datetime.datetime(2021, 3, 11, 0, 0), 554156.0, 8502.0, 1.5342250196695515),
 ('Bangladesh', datetime.datetime(2021, 3, 12, 0, 0), 555222.0, 8515.0, 1.5336207859198663),
 ('Bangladesh', datetime.datetime(2021, 3, 14, 0, 0), 557395.0, 8545.0, 1.5330241570161196),
 ('Bangladesh', datetime.datetime(2021, 3, 13, 0, 0), 556236.0, 8527.0, 1.5329824031526187),
 ('Bangladesh', datetime.datetime(2021, 3, 15, 0, 0), 559168.0, 8571.0, 1.5328130365113883),
 ('Bangladesh', datetime.datetime(2021, 3, 16, 0, 0), 560887.0, 8597.0, 1.5327508036378092),
 ('Bangladesh', datetime.datetime(2021, 2, 16, 0, 0), 541434.0, 8298.0, 1.5325967707975487),
 ('Bangladesh', datetime.datetime(2021, 2, 15, 0, 0), 541038.0, 8285.0, 1.531315730133558),
 ('Bangladesh', datetime.datetime(2021, 2, 14, 0, 0), 540592.0, 8274.0, 1.530544292183384),
 ('Bangladesh', datetime.datetime(2021, 2, 13, 0, 0), 540266.0, 8266.0, 1.5299870804381546),
 ('Bangladesh', datetime.datetime(2021, 3, 17, 0, 0), 562752.0, 8608.0, 1.5296258387353576),
 ('Bangladesh', datetime.datetime(2021, 2, 11, 0, 0), 539531.0, 8248.0, 1.528735142188308),
 ('Bangladesh', datetime.datetime(2021, 2, 12, 0, 0), 539975.0, 8253.0, 1.5284040927820732),
 ('Bangladesh', datetime.datetime(2021, 2, 10, 0, 0), 539153.0, 8239.0, 1.5281376529482356),
 ('Bangladesh', datetime.datetime(2021, 2, 9, 0, 0), 538765.0, 8229.0, 1.5273820682486798),
 ('Bangladesh', datetime.datetime(2021, 2, 8, 0, 0), 538378.0, 8221.0, 1.5269940450761361),
 ('Bangladesh', datetime.datetime(2021, 3, 18, 0, 0), 564939.0, 8624.0, 1.5265364933205179),
 ('Bangladesh', datetime.datetime(2021, 2, 7, 0, 0), 538062.0, 8205.0, 1.5249172028502291),
 ('Bangladesh', datetime.datetime(2021, 3, 19, 0, 0), 566838.0, 8642.0, 1.5245978568832717),
 ('Bangladesh', datetime.datetime(2021, 3, 20, 0, 0), 568706.0, 8668.0, 1.524161869225927),
 ('Bangladesh', datetime.datetime(2020, 5, 11, 0, 0), 15691.0, 239.0, 1.5231661461984578),
 ('Bangladesh', datetime.datetime(2021, 2, 6, 0, 0), 537770.0, 8190.0, 1.522955910519367),
 ('Bangladesh', datetime.datetime(2021, 2, 5, 0, 0), 537465.0, 8182.0, 1.5223316867144838),
 ('Bangladesh', datetime.datetime(2021, 2, 4, 0, 0), 537030.0, 8175.0, 1.5222613261828948)]